CREATE DATABASE tshirts;

USE tshirts;

CREATE TABLE product (
idProduct INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (100) NOT NULL, 
price FLOAT NOT NULL, 
stock INT NOT NULL
);

CREATE TABLE user (
idUser INT PRIMARY KEY AUTO_INCREMENT, 
user VARCHAR (45) NOT NULL,
name VARCHAR (45) NOT NULL, 
email VARCHAR (45) not null,
password VARCHAR(45) NOT NULL
);

CREATE TABLE orders (
idOrder INT PRIMARY KEY AUTO_INCREMENT,
nameProduct VARCHAR (45),
price FLOAT NOT NULL, 
description text
);